# Generated by Django 3.2.5 on 2022-07-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_group',
            field=models.CharField(choices=[('U', 'User'), ('M', 'Manager')], default='U', max_length=1),
        ),
    ]
