# Generated by Django 3.2.5 on 2022-08-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
