# Generated by Django 3.2.5 on 2022-06-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='sell_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
