# Generated by Django 3.2.5 on 2022-06-21 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('inventory', '0002_lossinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lossinventory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_loss', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='lossinventory',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_loss', to='inventory.manufacturer'),
        ),
        migrations.AlterField(
            model_name='lossinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_loss', to='products.product'),
        ),
    ]
