# Generated by Django 3.2.5 on 2022-08-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_damaged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='damaged',
        ),
    ]
