# Generated by Django 3.2.5 on 2022-06-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderedproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
