# Generated by Django 3.2.5 on 2022-06-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_inventory_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='inProduction',
            new_name='shipped',
        ),
    ]
