# Generated by Django 3.2.5 on 2022-05-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrecipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rec_description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
