# Generated by Django 3.2.5 on 2022-06-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrecipe', '0004_auto_20220607_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
