# Generated by Django 3.2.5 on 2022-06-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.ImageField(default='null', null=True, upload_to=''),
        ),
    ]
