# Generated by Django 3.2.5 on 2022-06-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220609_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pic',
            field=models.ImageField(default='null', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='InStock',
        ),
    ]
