# Generated by Django 3.2.5 on 2022-06-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220613_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=7),
        ),
    ]
